name: smart_owl
description: A new Flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^4.0.0
  flutter_launcher_icons: ^0.7.0

  bloc_pattern: ^1.0.0
  rxdart: ^0.19.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:   
  android: true # indica que colocaremos o ícone novo no Android
  ios: true # indica que colocaremos o ícone novo no iOS
  image_path: "assets/icon/icoapp.png" # caminho para o ícone   

flutter:

  uses-material-design: true